### ISSUE TITLE
Set backgound-color for .wrap-guide

### ISSUE THREAD

**Issue by hkdobrev** [atom/atom-dark-ui#14]
[wrap-guide](https://github.com/atom/wrap-guide) does not colour the `.wrap-guide` line by default.

It would be nice if the default theme styles it in any way so at least it is visible.

**Comment by kevinsawicki** [comment]
This has been formalized into a syntax variable `@syntax-wrap-guide-color` and is also now included when generating themes using `apm init`, closing this out.
