### ISSUE TITLE
Tree-View font-size from Settings?

### ISSUE THREAD

**Issue by philipgiuliani** [atom/atom-dark-ui#24]
Feature Request: At the moment its possible to change the font-size of the editor in the settings, but the font-size of the tree-view remains unchanged. In my case 11px is a way to small. I have set it via the styles.less to 13px. Would it be possible to set the same font-size that the editor has?

https://github.com/atom/atom-dark-ui/blob/master/stylesheets/ui-variables.less#L75

I opened it now here, but i think its more http://github.com/atom/tree-view related.

**Comment by simurai** [comment]
Gonna close this for now. Not saying it will never happen (I hope it does), but it's currently not that easy to add, see https://github.com/atom/atom/issues/5735 for more infos about it.

**Comment by simurai** [comment]
@philipgiuliani In the meantime, you could override the tree-view sizes like this: https://github.com/atom/atom/issues/3792#issuecomment-76903215

**Comment by philipgiuliani** [comment]
Yes i already did that :+1: Its ok thanks! :)

**Comment by mobimation** [comment]
This worked fine on a Macbook Pro 17 (1920 pixels wide):
https://github.com/atom/atom/issues/3792#issuecomment-250812732
