### ISSUE TITLE
Tree View items with diff status that are selected don't show the diff status

### ISSUE THREAD

**Issue by lee-dohm** [atom/atom-dark-ui#43]
Unselected:

![screen shot 2015-03-12 at 9 10 14 am](https://cloud.githubusercontent.com/assets/1038121/6622089/a48d3a48-c897-11e4-8818-888d3b053e43.png)

Selected:

![screen shot 2015-03-12 at 9 10 38 am](https://cloud.githubusercontent.com/assets/1038121/6622099/b330114c-c897-11e4-8000-d6ccd35fed1f.png)

**Comment by simurai** [comment]
I quickly tried it out:

![screen shot 2015-03-12 at 3 41 24 pm](https://cloud.githubusercontent.com/assets/378023/6629722/78a1e23a-c8ce-11e4-8385-ce401334ac2d.png)

![screen shot 2015-03-12 at 3 41 10 pm](https://cloud.githubusercontent.com/assets/378023/6629726/7dd161c2-c8ce-11e4-83d0-0f0d09844f02.png)

I think the green and orange would reduce the readability a bit on top of the blue background. Maybe still ok? An option would be to remove the blue background, but it's kinda the signature of the Atom themes.

**Comment by lee-dohm** [comment]
Maybe a white text drop shadow (or whatever the CSS is) only when selected to increase the contrast with the blue?
