### ISSUE TITLE
Markdown-preview is too bright

### ISSUE THREAD

**Issue by rugk** [atom/atom-dark-ui#50]
This does not look nice:
![markdownpreviewdesigntest](https://cloud.githubusercontent.com/assets/11966684/9531268/61685caa-4d05-11e5-977e-37011472cdce.PNG)

UI: Atom dark
Syntax: One dark
(only with one dark as the preview looks dark too)

Here is a complete discussion of the issue: https://github.com/atom/markdown-preview/issues/296

**Comment by simurai** [comment]
An option would be to add the [same styles](https://github.com/atom/one-dark-ui/blob/master/styles/packages.less#L75-L129) as One dark also to Atom dark.

On the other hand, might also be worth considering https://github.com/atom/markdown-preview/issues/6 again. So that all dark themes would be dark. You can still change it back to GitHub.com style (white).

**Comment by rugk** [comment]
From https://github.com/atom/markdown-preview/issues/6 I saw that the idea was implemented in one-dark-ui (https://github.com/atom/one-dark-ui/pull/20) .
So yes something similar (or even the same) would be great.

**Comment by simurai** [comment]
Adding it to One dark was more a test how it would feel. I think if people want this in general, it would make sense to add it to all themes and thus make it part of the `markdown-preview` package. It would also be easier to make changes to `markdown-preview` without having to update all themes.

How about we open https://github.com/atom/markdown-preview/issues/296 again and I can give it a try to see how well that would work.

**Comment by mjboswell** [comment]
I'm in the opposite camp – I really love One Dark, but miss the standard styling (white bg / dark text) of Markdown Preview. Any idea how to fix that without changing the theme? I can't get it to work. @simurai

**Comment by rugk** [comment]
> Any idea how to fix that without changing the theme?

Yes, use the option "Use GitHub.com Style" implemented in https://github.com/atom/markdown-preview/pull/240.

**Comment by mjboswell** [comment]
@rugk I've looked through all this and still have no idea how to enable. :(

**Comment by rugk** [comment]
In the settings of the theme.

**Comment by mjboswell** [comment]
I've gone through every possible setting for the One Dark theme, and there is nothing similar to anything described in the this tread or atom/markdown-preview#240

**Comment by lee-dohm** [comment]
@mjboswell 

1. Open the Settings View
1. Click the Packages tab
1. Search for "preview" 
1. Click the Settings button for the markdown-preview package
1. Check the "Use GitHub.com style" box

**Comment by mjboswell** [comment]
@lee-dohm Thank you! I spent way too much time digging around for this!

**Comment by lee-dohm** [comment]
You're welcome :grinning:
