### ISSUE TITLE
Add pending tabs styling

### ISSUE THREAD

**Issue by benogle** [atom/atom-dark-ui#55]
Pending tabs might be super confusing without the italics on the tabs. See https://github.com/atom/atom/issues/10753

cc @simurai

**Comment by simurai** [comment]
The _italics_ already seem to work.

![screen shot 2016-02-11 at 9 59 28 am](https://cloud.githubusercontent.com/assets/378023/12967018/4569fd18-d0a6-11e5-90cd-0a2367413b53.png)

But something with the corners looks broken.

**Comment by Ben3eeE** [comment]
Closing this since the gif in the referenced PR has italics on the tabs so this probably never was an issue.
