### ISSUE TITLE
Tabs

### ISSUE THREAD

**Issue by torn4dom4n** [atom/atom-dark-ui#65]
I think this shouldn't appear:

![atom-dark-ui](https://cloud.githubusercontent.com/assets/16760489/20846367/f18afcc6-b8fb-11e6-8c67-f47c3d7a6801.png)

**Comment by simurai** [comment]
The blue line is intended to show where the tab will be inserted when dragging. It might took a bit odd because the tabs have not straight edges and are diagonal.

**Comment by torn4dom4n** [comment]
I can see that, but why not try another way to get to know. For example, it is possible to move tabs when you drag them like **Google Chrome**.

**Comment by simurai** [comment]
I see, yeah, Chrome's way of moving the tabs when dragging is much nicer.

Do you mind opening an issue in the [tabs](https://github.com/atom/tabs/issues) package. This theme only is concerned about the styling.

**Comment by torn4dom4n** [comment]
I will do it. Thank @simurai.
