### ISSUE TITLE
tabs do have too much left padding - waste of space

### ISSUE THREAD

**Issue by ssbarnea** [atom/atom-dark-ui#70]
### Description

Currently tabs do have too much left padding on them and they are wasting screen real-estate, displaying less of the filenames.

![styles less atom 2017-04-04 11-21-13](https://cloud.githubusercontent.com/assets/102495/24652252/0da45488-1929-11e7-8fcb-496b158b9838.png)

If there is no desire to change the default style to make it better use the space, please do at least provide information on how to tune the stylesheet in order to lower the amount of wasted space.

**Comment by simurai** [comment]
Base on the screenshot, this issue probably belongs to https://github.com/atom/one-dark-ui.

In Atom `1.17` the tabs of the One themes will be redesigned, see https://github.com/atom/one-light-ui/pull/96.

Here a gif with One Dark UI:

![tabs](https://cloud.githubusercontent.com/assets/378023/24795141/41275b4c-1bc3-11e7-86ee-fe2839e3405f.gif)

Any better? There is also the option to switch to a "minimum" size.

**Comment by ssbarnea** [comment]
You are right about "one-dark-ui", can you move the ticket?  (i cannot).

Still, the issue is still valid and cannot be fixed by using the UI options. I tried: Minimum + Compact mode and still, there is plenty of wasted left-padding space. In fact in my case there is a little bit more than in the screencast.

**Comment by Ben3eeE** [comment]
@ssbarnea The redesign is only available in Atom 1.17. The screencast shows the new look with less padding.

**Comment by ssbarnea** [comment]
@Ben3eeE Thanks for clarifying. In this case I would consider this issue sorted, even it the fix was not released yet.
